services:
  klara:
    build: 
      context: ./bot
      tags: 
        - klara:latest
    env_file: 
      - ./.env.prod
    networks: 
      - klara_bot
    depends_on:
      - redis
    
  redis:
    image: redis:latest
    networks: 
      - klara_bot

  log_service:
    build:
      context: ./log_service
    env_file:
      - ./.env.prod
    networks:
      - klara_bot
    depends_on:
      - redis
      - klara

networks:
  klara_bot:
    driver: bridge

volumes:
  neo4j_data:
